#include "header.h"
#include "Government_agent_header.h"
#include "my_library_header.h"


int Government_init(){


		TAX_RATE_CORPORATE = CONST_GENERAL_TAX_RATE;

		TAX_RATE_INCOME = CONST_GENERAL_TAX_RATE;


		SHORT_TERM_CAPITAL_GAIN_TAX_RATE = CONST_GENERAL_TAX_RATE;

		LONG_TERM_CAPITAL_GAIN_TAX_RATE = CONST_GENERAL_TAX_RATE;

		SHORT_TERM_CAPITAL_GAIN_ON_DIVIDEND_TAX_RATE = CONST_GENERAL_TAX_RATE;
		LONG_TERM_CAPITAL_GAIN_ON_DIVIDEND_TAX_RATE = CONST_GENERAL_TAX_RATE;


	return 0;
}



int Government_set_policy(){


	if(TAX_SCENARIO ==1 && DAY== CONST_TAX_POLICY_ITERATION){

		TAX_RATE_CORPORATE = CONST_TAX_RATE_POLICY;


	}

	add_policy_message(TAX_RATE_CORPORATE, TAX_RATE_INCOME, SHORT_TERM_CAPITAL_GAIN_TAX_RATE, LONG_TERM_CAPITAL_GAIN_TAX_RATE, SHORT_TERM_CAPITAL_GAIN_ON_DIVIDEND_TAX_RATE, LONG_TERM_CAPITAL_GAIN_ON_DIVIDEND_TAX_RATE);

	return 0;
}
